### ISSUE TITLE
[REQ] make it honour g:fzf_command_prefix

### ISSUE THREAD

**Issue by step-** [laher/fuzzymenu.vim#1]
Hi, very nice idea and I agree it's already useful even though still early work.  Would you please make it honour `g:fzf_command_prefix`?  For instance, when vimrc defines `let g:fzf_command_prefix = 'Fzf'` then fuzzymenu executes `:FzfFiles` instead of `:Files`.   Thank you.

**Comment by laher** [comment]
Good shout - fixed by above PR. Please update and try now

**Comment by step-** [comment]
I can confirm it works great now!   Thank you.
