### ISSUE TITLE
How to use fzf popup window

### ISSUE THREAD

**Issue by comfortablynick** [laher/fuzzymenu.vim#7]
Thanks for this plugin! It's a great 'command palette' type feature in vim.

I was wondering how to use the fzf popup with this? I have fzf generally configured to use the popup, which the other commands (`:FZF`, `:Commands`, `:Maps`, etc) use. The command `:Fzm` opens at the bottom of the window in a standard terminal pane.

This is my window config:
```vim
let g:fzf_layout = {'window': {'height': 0.6, 'width': 0.9}}
```

**Comment by laher** [comment]
Hi Nick. Fuzzymenu I added the following layout config:

```
let g:fuzzymenu_position =  'down'
let g:fuzzymenu_size = '33%'
```

Thinking about it you could probably do the following ... (sorry can't try right now):

```
let g:fuzzymenu_position =  'window'
let g:fuzzymenu_size = {'height': 0.6, 'width': 0.9}
```

which makes me realize I could do a couple of things here:

 * create a `g:fuzzymenu_layout` option, or ...
 * create a `g:fuzzymenu_use_fzf_layout = 1` option

It wouldn't be too hard to adjust for this ...

**Comment by comfortablynick** [comment]
I just got around to checking this. The floating window works, but the width calculation is based on `winwidth(0)`, so the right column is cut off. That may require some refactoring...I'll just use the standard window position for now.

**Comment by laher** [comment]
Right. Thanks for looking into this. I'm going to mark this as 'Milestone 8', because I'm adding a bunch of features, and I'm not sure how best to provide customisability yet.

The current approach is wonky (as you said, a refactor is needed). I'm gonna add a bunch more things over the coming months (M5,M6,M7) and then revisit.

In the meantime, I'll just leave this open and tagged. Ta.

**Comment by laher** [comment]
@comfortablynick I've made a PR that just inherits from fzf layout, and adjusts the column width for _some_ fzf layouts..

https://github.com/laher/fuzzymenu.vim/pull/15

I'm leaning towards just merging it. LMK if you think it's better or not

**Comment by comfortablynick** [comment]
@laher thanks, I commented on the PR with my results.

**Comment by laher** [comment]
closing because of https://github.com/laher/fuzzymenu.vim/pull/15
