### ISSUE TITLE
slow response when mapping :Fzm

### ISSUE THREAD

**Issue by tfriedel** [laher/fuzzymenu.vim#8]
First of all I want to say I really like this plugin! I've been looking for something like the command palette or a cheat sheet for Vim and this almost fits the bill! I find it's great for  also triggering the command, but  less great for the cheat sheet use case where I would for example say
comment block of code - C-V, select lines, S-I, #, Esc

Anyway, here's an issue I had and solved:

I noticed when I used a mapping like
```  nmap <Leader>m <Plug>Fzm``` it took between 1.5 and 2 sec for the menu to appear. This seemed odd.
I tried using nnoremap instead, but this didn't work at all. I think there must be some recursive rebinding in Fzm going on, otherwise it should work. 
Anyway, I replaced the mapping now with
``` nmap <Leader>m :call fuzzymenu#Run({})<cr> ```
and now the menu appears instantly. 

I suggest you change the suggested mappings or somehow fix <Plug>Fzm.

**Comment by laher** [comment]
Good shout. I've updated the suggested mappings for now, I can't seem to work out why there's a delay on the <Plug> mappings.

btw, visual mode things are a bit of a work in progress. I'm hoping to make it more intuitive but it's going to take a bit of doing. I'll ping you if I get somewhere useful with it

**Comment by laher** [comment]
I've just put up a github project with some very loose milestones. 'Making visual mode good' is next-up after I'm done with the current milestone. https://github.com/laher/fuzzymenu.vim/projects/1

I'll tag this as M6 and leave it open
